# fly.toml app configuration file generated for pokedex-sni153 on 2024-04-17T10:56:40-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pokedex-sni153'
primary_region = 'sea'

[build]

[deploy]
  strategy = "canary"

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
